import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Kondosoft talent
        </h1>
        <ul>
          <li>
            <Link href='/carlos-gonzalez'>
              <a>Carlos Gonzalez</a>
            </Link>
          </li>
          <li>
            <Link href='/luis-juarez'>
              <a>Luis Juarez</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  )
}
